# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 400)
        MainWindow.setMinimumSize(QtCore.QSize(600, 400))
        MainWindow.setMaximumSize(QtCore.QSize(600, 400))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.button_encrypt = QtWidgets.QPushButton(self.centralwidget)
        self.button_encrypt.setGeometry(QtCore.QRect(400, 360, 70, 23))
        self.button_encrypt.setObjectName("button_encrypt")
        self.button_decryptor = QtWidgets.QPushButton(self.centralwidget)
        self.button_decryptor.setGeometry(QtCore.QRect(490, 360, 75, 23))
        self.button_decryptor.setObjectName("button_decryptor")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(10, 10, 571, 341))
        self.stackedWidget.setObjectName("stackedWidget")
        self.Chat_page = QtWidgets.QWidget()
        self.Chat_page.setObjectName("Chat_page")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.Chat_page)
        self.plainTextEdit.setGeometry(QtCore.QRect(0, 40, 571, 221))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.send_button = QtWidgets.QPushButton(self.Chat_page)
        self.send_button.setGeometry(QtCore.QRect(470, 280, 75, 23))
        self.send_button.setObjectName("send_button")
        self.msg_box = QtWidgets.QTextEdit(self.Chat_page)
        self.msg_box.setGeometry(QtCore.QRect(10, 280, 421, 21))
        self.msg_box.setObjectName("msg_box")
        self.pushButton_3 = QtWidgets.QPushButton(self.Chat_page)
        self.pushButton_3.setGeometry(QtCore.QRect(174, 310, 201, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.con_to_label = QtWidgets.QLabel(self.Chat_page)
        self.con_to_label.setGeometry(QtCore.QRect(16, 10, 271, 20))
        self.con_to_label.setText("")
        self.con_to_label.setObjectName("con_to_label")
        self.token_label = QtWidgets.QLabel(self.Chat_page)
        self.token_label.setGeometry(QtCore.QRect(316, 10, 201, 20))
        self.token_label.setText("")
        self.token_label.setObjectName("token_label")
        self.stackedWidget.addWidget(self.Chat_page)
        self.Home = QtWidgets.QWidget()
        self.Home.setObjectName("Home")
        self.connect_ip_button = QtWidgets.QPushButton(self.Home)
        self.connect_ip_button.setGeometry(QtCore.QRect(420, 250, 75, 23))
        self.connect_ip_button.setObjectName("connect_ip_button")
        self.start_server_button = QtWidgets.QPushButton(self.Home)
        self.start_server_button.setGeometry(QtCore.QRect(160, 70, 241, 51))
        self.start_server_button.setObjectName("start_server_button")
        self.label = QtWidgets.QLabel(self.Home)
        self.label.setGeometry(QtCore.QRect(260, 180, 47, 13))
        self.label.setObjectName("label")
        self.ip_input = QtWidgets.QLineEdit(self.Home)
        self.ip_input.setGeometry(QtCore.QRect(150, 250, 151, 20))
        self.ip_input.setObjectName("ip_input")
        self.port_input = QtWidgets.QLineEdit(self.Home)
        self.port_input.setGeometry(QtCore.QRect(312, 250, 91, 20))
        self.port_input.setObjectName("port_input")
        self.stackedWidget.addWidget(self.Home)
        self.EncryptorWindow = QtWidgets.QWidget()
        self.EncryptorWindow.setObjectName("EncryptorWindow")
        self.label_2 = QtWidgets.QLabel(self.EncryptorWindow)
        self.label_2.setGeometry(QtCore.QRect(10, 30, 111, 31))
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.EncryptorWindow)
        self.label_4.setGeometry(QtCore.QRect(320, 190, 71, 21))
        self.label_4.setObjectName("label_4")
        self.En_Input_msg = QtWidgets.QTextEdit(self.EncryptorWindow)
        self.En_Input_msg.setGeometry(QtCore.QRect(140, 20, 261, 71))
        self.En_Input_msg.setObjectName("En_Input_msg")
        self.button_en_msg = QtWidgets.QPushButton(self.EncryptorWindow)
        self.button_en_msg.setGeometry(QtCore.QRect(450, 40, 91, 23))
        self.button_en_msg.setObjectName("button_en_msg")
        self.Access_code = QtWidgets.QLabel(self.EncryptorWindow)
        self.Access_code.setGeometry(QtCore.QRect(410, 190, 101, 16))
        self.Access_code.setText("")
        self.Access_code.setObjectName("Access_code")
        self.label_9 = QtWidgets.QLabel(self.EncryptorWindow)
        self.label_9.setGeometry(QtCore.QRect(10, 230, 47, 13))
        self.label_9.setObjectName("label_9")
        self.textBrowser = QtWidgets.QTextBrowser(self.EncryptorWindow)
        self.textBrowser.setGeometry(QtCore.QRect(60, 220, 471, 101))
        self.textBrowser.setObjectName("textBrowser")
        self.stackedWidget.addWidget(self.EncryptorWindow)
        self.DecryptorWindow = QtWidgets.QWidget()
        self.DecryptorWindow.setObjectName("DecryptorWindow")
        self.label_15 = QtWidgets.QLabel(self.DecryptorWindow)
        self.label_15.setGeometry(QtCore.QRect(6, 20, 111, 20))
        self.label_15.setObjectName("label_15")
        self.pushButton = QtWidgets.QPushButton(self.DecryptorWindow)
        self.pushButton.setGeometry(QtCore.QRect(444, 30, 101, 23))
        self.pushButton.setObjectName("pushButton")
        self.label_17 = QtWidgets.QLabel(self.DecryptorWindow)
        self.label_17.setGeometry(QtCore.QRect(200, 160, 81, 20))
        self.label_17.setObjectName("label_17")
        self.lineEdit = QtWidgets.QLineEdit(self.DecryptorWindow)
        self.lineEdit.setGeometry(QtCore.QRect(290, 160, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.textEdit = QtWidgets.QTextEdit(self.DecryptorWindow)
        self.textEdit.setGeometry(QtCore.QRect(123, 10, 291, 71))
        self.textEdit.setObjectName("textEdit")
        self.label_18 = QtWidgets.QLabel(self.DecryptorWindow)
        self.label_18.setGeometry(QtCore.QRect(30, 270, 47, 13))
        self.label_18.setObjectName("label_18")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.DecryptorWindow)
        self.textBrowser_3.setGeometry(QtCore.QRect(100, 220, 431, 111))
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.stackedWidget.addWidget(self.DecryptorWindow)
        self.Error_msg = QtWidgets.QLabel(self.centralwidget)
        self.Error_msg.setGeometry(QtCore.QRect(6, 359, 311, 31))
        self.Error_msg.setText("")
        self.Error_msg.setObjectName("Error_msg")
        self.home_button = QtWidgets.QPushButton(self.centralwidget)
        self.home_button.setGeometry(QtCore.QRect(330, 360, 61, 23))
        self.home_button.setObjectName("home_button")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.button_encrypt.setText(_translate("MainWindow", "Encryptor"))
        self.button_decryptor.setText(_translate("MainWindow", "Decryptor"))
        self.send_button.setText(_translate("MainWindow", "Send"))
        self.pushButton_3.setText(_translate("MainWindow", "Close Connection"))
        self.connect_ip_button.setText(_translate("MainWindow", "Connect"))
        self.start_server_button.setText(_translate("MainWindow", "Start Server"))
        self.label.setText(_translate("MainWindow", "Or"))
        self.ip_input.setPlaceholderText(_translate("MainWindow", "Enter IP"))
        self.port_input.setPlaceholderText(_translate("MainWindow", "Enter port"))
        self.label_2.setText(_translate("MainWindow", "Message Encryption :-"))
        self.label_4.setText(_translate("MainWindow", "Access Code :- "))
        self.button_en_msg.setText(_translate("MainWindow", "Encrypt Message"))
        self.label_9.setText(_translate("MainWindow", "Output :- "))
        self.label_15.setText(_translate("MainWindow", "Message Decryption :-"))
        self.pushButton.setText(_translate("MainWindow", "Decrypt Message"))
        self.label_17.setText(_translate("MainWindow", "Access Code :-"))
        self.label_18.setText(_translate("MainWindow", "Output :-"))
        self.home_button.setText(_translate("MainWindow", "Home"))
